// Mocks generated by Mockito 5.2.0 from annotations
// in curso_clean_solid/test/data/usercases/load_surveys/remote_load_surveys_teste.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'remote_load_surveys_teste.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [HttpClientSpy].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientSpy extends _i1.Mock implements _i2.HttpClientSpy {
  MockHttpClientSpy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<dynamic, dynamic>?> request(
          {String? url, String? method, Map<dynamic, dynamic>? body}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #request, [], {#url: url, #method: method, #body: body}),
              returnValue: Future<Map<dynamic, dynamic>?>.value())
          as _i3.Future<Map<dynamic, dynamic>?>);
}
